steps:
  # Step 1: Build the container image using the root Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:latest'
      - '.'

  # Step 2: Push the container image to Artifact Registry / GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$COMMIT_SHA'

  # Step 3: Deploy image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hercules-gym-api'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$COMMIT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:latest'
