import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type AppLanguage = 'en' | 'bn';

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: string, vars?: Record<string, string | number>) => string;
  languageLabel: string;
}

const LANGUAGE_STORAGE_KEY = 'app_language';

const LANGUAGE_LABELS: Record<AppLanguage, string> = {
  en: 'English',
  bn: 'বাংলা',
};

const BN_TRANSLATIONS: Record<string, string> = {
  'Home': 'হোম',
  'Members': 'সদস্য',
  'Approvals': 'অনুমোদন',
  'Attendance': 'উপস্থিতি',
  'Shop': 'দোকান',
  'Chat': 'চ্যাট',
  'Profile': 'প্রোফাইল',
  'Language': 'ভাষা',
  'Select app language': 'অ্যাপের ভাষা নির্বাচন করুন',
  'Welcome back! Login to continue': 'আবার স্বাগতম! চালিয়ে যেতে লগইন করুন',
  'Email or +91 phone': 'ইমেইল বা +৯১ ফোন',
  'Password': 'পাসওয়ার্ড',
  'Login': 'লগইন',
  "Don't have an account?": 'অ্যাকাউন্ট নেই?',
  'Register': 'রেজিস্টার',
  'Error': 'ত্রুটি',
  'Please fill in all fields': 'সব ঘর পূরণ করুন',
  'Login Failed': 'লগইন ব্যর্থ',
  'Create Account': 'অ্যাকাউন্ট তৈরি করুন',
  'Join Hercules Gym today': 'আজই হারকিউলিস জিমে যোগ দিন',
  'I am a:': 'আমি:',
  'Member': 'মেম্বার',
  'Trainer': 'ট্রেইনার',
  'Admin': 'অ্যাডমিন',
  'Select Gym Center:': 'জিম সেন্টার নির্বাচন করুন:',
  'Full Name': 'পূর্ণ নাম',
  'Email': 'ইমেইল',
  '10-digit mobile number': '১০ সংখ্যার মোবাইল নম্বর',
  'Confirm Password': 'পাসওয়ার্ড নিশ্চিত করুন',
  'Already have an account?': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
  'Invalid Email': 'অবৈধ ইমেইল',
  'Please enter a valid email address to continue.': 'চালিয়ে যেতে একটি বৈধ ইমেইল ঠিকানা দিন।',
  'Phone must be exactly 10 digits': 'ফোন নম্বর অবশ্যই ১০ সংখ্যার হতে হবে',
  'Passwords do not match': 'পাসওয়ার্ড মেলেনি',
  'Password must be at least 6 characters': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
  'Please select a gym center': 'একটি জিম সেন্টার নির্বাচন করুন',
  'Registration Submitted': 'রেজিস্ট্রেশন জমা হয়েছে',
  'Your registration is pending approval from the primary admin.': 'আপনার রেজিস্ট্রেশন প্রাইমারি অ্যাডমিনের অনুমোদনের অপেক্ষায় আছে।',
  'Your registration is pending approval from a trainer at your center.': 'আপনার রেজিস্ট্রেশন আপনার সেন্টারের ট্রেইনারের অনুমোদনের অপেক্ষায় আছে।',
  'Registration Failed': 'রেজিস্ট্রেশন ব্যর্থ',
  'Welcome back,': 'আবার স্বাগতম,',
  'Quick Actions': 'দ্রুত কাজ',
  'Check In': 'চেক-ইন',
  'Payments': 'পেমেন্ট',
  'Messages': 'বার্তা',
  'Announcements': 'ঘোষণা',
  'No announcements yet': 'এখনও কোনো ঘোষণা নেই',
  'Confirm Payment': 'পেমেন্ট নিশ্চিত করুন',
  'Total: Rs.{amount}\n\nProceed to pay for these items now?': 'মোট: Rs.{amount}\n\nএখনই কি এসব আইটেমের পেমেন্ট করবেন?',
  'Payment successful - do collect your items from the gym.': 'পেমেন্ট সফল - জিম থেকে আপনার আইটেম সংগ্রহ করুন।',
  'Payment failed. Please try again.': 'পেমেন্ট ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
  'Payment now - Collect items at gym': 'এখন পেমেন্ট করুন - জিম থেকে আইটেম সংগ্রহ করুন',
  'Approval Pending': 'অনুমোদন অপেক্ষমাণ',
  'Your registration is awaiting approval. You will be notified once it is approved.': 'আপনার রেজিস্ট্রেশন অনুমোদনের অপেক্ষায় আছে। অনুমোদন হলে আপনাকে জানানো হবে।',
  'Check Status': 'স্ট্যাটাস দেখুন',
  'All Centers': 'সব সেন্টার',
  'Total Members': 'মোট সদস্য',
  'Active': 'সক্রিয়',
  'Trainers': 'ট্রেইনাররা',
  "Today's Attendance": 'আজকের উপস্থিতি',
  'This Month Revenue': 'এই মাসের আয়',
  'Pending Approvals': 'অপেক্ষমাণ অনুমোদন',
  'Pending Orders': 'অপেক্ষমাণ অর্ডার',
  'Expiring Soon': 'শিগগির মেয়াদ শেষ',
  'Your Center': 'আপনার সেন্টার',
  'Assigned Members': 'নির্ধারিত সদস্য',
  'Unread Messages': 'অপঠিত বার্তা',
  'Payment Due!': 'পেমেন্ট বাকি!',
  'Your subscription payment is due. Please contact the gym.': 'আপনার সাবস্ক্রিপশনের পেমেন্ট বাকি। দয়া করে জিমে যোগাযোগ করুন।',
  'Membership payment due on {date}. Total Rs.{amount}.': 'মেম্বারশিপ পেমেন্ট {date} তারিখে বকেয়া। মোট Rs.{amount}।',
  'Late fee applied: Rs.{fee}': 'লেট ফি যোগ হয়েছে: Rs.{fee}',
  'Active Membership': 'সক্রিয় মেম্বারশিপ',
  'Membership Expired': 'মেম্বারশিপের মেয়াদ শেষ',
  'Membership payment successful.': 'মেম্বারশিপ পেমেন্ট সফল হয়েছে।',
  'Failed to pay membership fee': 'মেম্বারশিপ ফি পরিশোধ ব্যর্থ',
  'Membership Payment': 'মেম্বারশিপ পেমেন্ট',
  'Due Date: {date}': 'নির্ধারিত তারিখ: {date}',
  'Base Fee: Rs.{amount}': 'মূল ফি: Rs.{amount}',
  'Late Fee: Rs.{amount}': 'লেট ফি: Rs.{amount}',
  'Total Payable: Rs.{amount}': 'মোট পরিশোধযোগ্য: Rs.{amount}',
  'Pay Now': 'এখনই পরিশোধ করুন',
  'No payment due right now': 'এই মুহূর্তে কোনো পেমেন্ট বাকি নেই',
  'Last 3 Membership Payments': 'শেষ ৩টি মেম্বারশিপ পেমেন্ট',
  'No membership payment history': 'মেম্বারশিপ পেমেন্টের ইতিহাস নেই',
  'Last 3 Shop Payments': 'শেষ ৩টি শপ পেমেন্ট',
  'No shop payment history': 'শপ পেমেন্টের ইতিহাস নেই',
  'Rs.{amount}': 'Rs.{amount}',
  'Achievements': 'অর্জন',
  'No achievements added yet': 'এখনও কোনো অর্জন যোগ করা হয়নি',
  'Member ID: {id}': 'মেম্বার আইডি: {id}',
  'This Month': 'এই মাস',
  "Today's Workout": 'আজকের ওয়ার্কআউট',
  'Notifications': 'নোটিফিকেশন',
  'Center': 'সেন্টার',
  'In': 'ইন',
  'Out': 'আউট',
  '{days} days remaining': '{days} দিন বাকি',
  'Primary Admin': 'প্রাইমারি অ্যাডমিন',
  '{count} selected': '{count}টি নির্বাচিত',
  'Delete Announcement': 'ঘোষণা মুছুন',
  'This announcement will be removed for all users.': 'এই ঘোষণাটি সকল ব্যবহারকারীর জন্য মুছে যাবে।',
  'Cancel': 'বাতিল',
  'Delete': 'মুছুন',
  'Failed to delete announcement': 'ঘোষণা মুছতে ব্যর্থ',
  'No conversations yet': 'এখনও কোনো কথোপকথন নেই',
  'Start a conversation': 'কথোপকথন শুরু করুন',
  'Delete chat': 'চ্যাট মুছুন',
  'Delete all messages with {name}?': '{name}-এর সাথে সব বার্তা মুছবেন?',
  'Failed': 'ব্যর্থ',
  'Failed to delete conversation': 'কথোপকথন মুছতে ব্যর্থ',
  'You can message admin, trainers, and members from your branch': 'আপনি আপনার ব্রাঞ্চের অ্যাডমিন, ট্রেইনার এবং সদস্যদের বার্তা পাঠাতে পারবেন',
  'You can message all members and trainers in your branch, and all admins': 'আপনি আপনার ব্রাঞ্চের সব সদস্য ও ট্রেইনারকে এবং সব অ্যাডমিনকে বার্তা পাঠাতে পারবেন',
  'You can message all members and trainers': 'আপনি সব সদস্য ও ট্রেইনারকে বার্তা পাঠাতে পারবেন',
  'Success': 'সফল',
  'You have been checked in!': 'আপনার চেক-ইন সম্পন্ন হয়েছে!',
  'Failed to check in': 'চেক-ইন ব্যর্থ',
  'You have been checked out!': 'আপনার চেক-আউট সম্পন্ন হয়েছে!',
  'Failed to check out': 'চেক-আউট ব্যর্থ',
  'Unknown': 'অজানা',
  'Present': 'উপস্থিত',
  'Still checked in': 'এখনও চেক-ইন রয়েছে',
  'No attendance records for today': 'আজকের কোনো উপস্থিতির রেকর্ড নেই',
  'No attendance history': 'উপস্থিতির ইতিহাস নেই',
  'Check Out': 'চেক-আউট',
  'You are currently checked in': 'আপনি বর্তমানে চেক-ইন আছেন',
  'You are currently checked in. Use QR to check out.': 'আপনি বর্তমানে চেক-ইন আছেন। চেক-আউট করতে কিউআর ব্যবহার করুন।',
  'Tap to check in': 'চেক-ইন করতে ট্যাপ করুন',
  'My History': 'আমার ইতিহাস',
  'Duration: {duration}': 'সময়কাল: {duration}',
  'Today ({count})': 'আজ ({count})',
  'Last {count} Months': 'শেষ {count} মাস',
  'Delete messages': 'বার্তা মুছুন',
  'Delete {count} selected message(s)?': 'নির্বাচিত {count}টি বার্তা মুছবেন?',
  'Unable to delete selected messages': 'নির্বাচিত বার্তা মুছতে পারিনি',
  'Delete full chat': 'পুরো চ্যাট মুছুন',
  'This will permanently remove the entire conversation.': 'এতে পুরো কথোপকথন স্থায়ীভাবে মুছে যাবে।',
  'Unable to delete full chat': 'পুরো চ্যাট মুছতে পারিনি',
  'Send failed': 'পাঠানো ব্যর্থ',
  'Unable to send message': 'বার্তা পাঠানো যায়নি',
  'Choose action': 'অ্যাকশন নির্বাচন করুন',
  'User': 'ব্যবহারকারী',
  'No messages yet. Start the conversation!': 'এখনও কোনো বার্তা নেই। কথোপকথন শুরু করুন!',
  'Type a message...': 'বার্তা লিখুন...',
  'Expired': 'মেয়াদোত্তীর্ণ',
  'Start': 'শুরু',
  'Expires': 'মেয়াদ শেষ',
  'Visits': 'ভিজিট',
  'Day Streak': 'টানা দিন',
  'Goals': 'লক্ষ্য',
  'Account': 'অ্যাকাউন্ট',
  'Edit Profile': 'প্রোফাইল সম্পাদনা',
  'QR Check-In': 'কিউআর চেক-ইন',
  'Attendance QR': 'উপস্থিতি কিউআর',
  'Use this single QR for both check-in and check-out.': 'চেক-ইন ও চেক-আউট দুটোর জন্য এই একটি কিউআর ব্যবহার করুন।',
  'Date': 'তারিখ',
  'Daily QR codes are generated for check-in and check-out.': 'চেক-ইন ও চেক-আউটের জন্য প্রতিদিন নতুন কিউআর কোড তৈরি হয়।',
  'Unable to load check-in QR': 'চেক-ইন কিউআর লোড করা যায়নি',
  'Unable to load check-out QR': 'চেক-আউট কিউআর লোড করা যায়নি',
  'Unable to load attendance QR': 'উপস্থিতি কিউআর লোড করা যায়নি',
  'Body Metrics': 'বডি মেট্রিকস',
  'My Workouts': 'আমার ওয়ার্কআউট',
  'My Diet Plan': 'আমার ডায়েট প্ল্যান',
  'Preferences': 'পছন্দসমূহ',
  'Light Mode': 'লাইট মোড',
  'Dark Mode': 'ডার্ক মোড',
  'Support': 'সহায়তা',
  'Help & Support': 'সহায়তা ও সাপোর্ট',
  'Terms of Service': 'সেবার শর্তাবলি',
  'Privacy Policy': 'গোপনীয়তা নীতি',
  'Logout': 'লগআউট',
  'Built by Rounak Saha': 'রৌণক সাহা নির্মিত',
  'Contributions: product architecture, frontend and backend engineering, deployment, and quality improvements.': 'অবদান: প্রোডাক্ট আর্কিটেকচার, ফ্রন্টএন্ড ও ব্যাকএন্ড ইঞ্জিনিয়ারিং, ডিপ্লয়মেন্ট এবং কোয়ালিটি উন্নয়ন।',
  'Are you sure you want to logout from your account?': 'আপনি কি নিশ্চিত যে অ্যাকাউন্ট থেকে লগআউট করতে চান?',
  'No Plan': 'কোনো প্ল্যান নেই',
  '{days}d left': '{days} দিন বাকি',
  'Search members...': 'সদস্য খুঁজুন...',
  'Total': 'মোট',
  'Inactive': 'নিষ্ক্রিয়',
  'No members found': 'কোনো সদস্য পাওয়া যায়নি',
  'No members yet': 'এখনও কোনো সদস্য নেই',
  'Access denied': 'অ্যাক্সেস নেই',
  'Search trainers...': 'ট্রেইনার খুঁজুন...',
  'No center': 'কোনো সেন্টার নেই',
  'members': 'সদস্য',
  'No trainers found': 'কোনো ট্রেইনার পাওয়া যায়নি',
  'No trainers available': 'কোনো ট্রেইনার উপলব্ধ নয়',
  'Approval Flow': 'অনুমোদন প্রবাহ',
  'Requested': 'অনুরোধকৃত',
  'Under Review': 'পর্যালোচনাধীন',
  'Approved': 'অনুমোদিত',
  'Approve': 'অনুমোদন করুন',
  'Reject': 'প্রত্যাখ্যান করুন',
  'Loading approvals...': 'অনুমোদনের তথ্য লোড হচ্ছে...',
  'All Caught Up!': 'সব আপডেট সম্পন্ন!',
  'No pending approval requests': 'কোনো অপেক্ষমাণ অনুমোদন অনুরোধ নেই',
  'Approve Registration?': 'রেজিস্ট্রেশন অনুমোদন করবেন?',
  'Welcome {name} to Hercules Gym?': '{name}-কে কি হারকিউলিস জিমে স্বাগতম জানাবেন?',
  'Reject Registration': 'রেজিস্ট্রেশন প্রত্যাখ্যান করুন',
  'Provide a reason (optional)': 'কারণ লিখুন (ঐচ্ছিক)',
  'Enter reason for rejection...': 'প্রত্যাখ্যানের কারণ লিখুন...',
  'OK': 'ঠিক আছে',
  'Synced': 'সিঙ্ক হয়েছে',
  'Action Failed': 'অ্যাকশন ব্যর্থ',
  'Request was already processed. The list is now up to date.': 'অনুরোধটি আগেই প্রক্রিয়াজাত হয়েছে। তালিকা এখন আপডেট।',
  '{name} has been approved successfully.': '{name} সফলভাবে অনুমোদিত হয়েছে।',
  '{name} request has been rejected.': '{name}-এর অনুরোধ প্রত্যাখ্যান করা হয়েছে।',
  'Long press a chat to delete conversation history': 'কথোপকথনের ইতিহাস মুছতে চ্যাটে লং প্রেস করুন',
  'Revenues': 'আয়',
  'Revenue Summary': 'আয়ের সারসংক্ষেপ',
  'Total Revenue': 'মোট আয়',
  'Total Payments: {count}': 'মোট পেমেন্ট: {count}',
  'Payments: {count}': 'পেমেন্ট: {count}',
  'Gym Subscription Revenue': 'জিম সাবস্ক্রিপশন আয়',
  'Shop Revenue': 'শপ আয়',
  'Monthly Revenue': 'মাসিক আয়',
  'Payment History': 'পেমেন্ট ইতিহাস',
  'Membership': 'মেম্বারশিপ',
  'Mode: {method}': 'মোড: {method}',
  'Center: {center}': 'সেন্টার: {center}',
  'No payment history found': 'কোনো পেমেন্ট ইতিহাস পাওয়া যায়নি',
  'Gallery permission is required to upload screenshot.': 'স্ক্রিনশট আপলোড করতে গ্যালারির অনুমতি প্রয়োজন।',
  'Could not process selected image. Please try another screenshot.': 'নির্বাচিত ছবি প্রক্রিয়া করা যায়নি। অনুগ্রহ করে অন্য স্ক্রিনশট দিন।',
  'Please upload payment screenshot first': 'অনুগ্রহ করে আগে পেমেন্টের স্ক্রিনশট আপলোড করুন',
  'Payment screenshot submitted. Awaiting admin confirmation.': 'পেমেন্টের স্ক্রিনশট জমা হয়েছে। অ্যাডমিন যাচাইয়ের অপেক্ষায় আছে।',
  'Failed to submit membership payment proof': 'মেম্বারশিপ পেমেন্ট প্রুফ জমা দিতে ব্যর্থ হয়েছে',
  'Screenshot not available': 'স্ক্রিনশট পাওয়া যায়নি',
  'Change screenshot': 'স্ক্রিনশট বদলান',
  'Upload payment screenshot': 'পেমেন্টের স্ক্রিনশট আপলোড করুন',
  'Submit for Verification': 'যাচাইয়ের জন্য জমা দিন',
  'Pending Verification': 'যাচাই অপেক্ষমান',
  'No pending submissions': 'কোনো অপেক্ষমান জমা নেই',
  'Payment Error': 'পেমেন্ট ত্রুটি',
  'Upload screenshot': 'স্ক্রিনশট আপলোড করুন',
  'Please upload payment screenshot to continue.': 'চালিয়ে যেতে পেমেন্টের স্ক্রিনশট আপলোড করুন।',
  'Submit Shop Payment': 'শপ পেমেন্ট জমা দিন',
  'Total: Rs.{amount}\n\nSubmit screenshot to admin for payment verification?': 'মোট: Rs.{amount}\n\nযাচাইয়ের জন্য অ্যাডমিনকে স্ক্রিনশট পাঠাবেন?',
  'Submit': 'জমা দিন',
  'Failed to submit payment proof. Please try again.': 'পেমেন্ট প্রুফ জমা দিতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
  'After admin confirmation, collect items at gym': 'অ্যাডমিন নিশ্চিত করার পর জিম থেকে আইটেম সংগ্রহ করুন',
  'Open Payments': 'পেমেন্ট খুলুন',
  'Fitness. Discipline. Progress.': 'ফিটনেস। শৃঙ্খলা। অগ্রগতি।',
  'Open instantly, train consistently': 'দ্রুত খুলুন, নিয়মিত ট্রেন করুন',
  'Core home screen loads first. Login/register continues online when you are ready.': 'প্রথমে হোম স্ক্রিন লোড হবে। আপনি প্রস্তুত হলে লগইন/রেজিস্টার করে অনলাইন প্রক্রিয়া চালু করুন।',
  "Welcome to your hometown's first ever gym digital app services presented to you by Hercules Gym - We stand strong with Fitness, Discipline and Progress !!":
    'আপনার নিজ শহরের প্রথম জিম ডিজিটাল অ্যাপ সার্ভিসে স্বাগতম, হারকিউলিস জিমের পক্ষ থেকে। আমরা ফিটনেস, শৃঙ্খলা ও অগ্রগতির সাথে দৃঢ়ভাবে আপনার পাশে আছি!!',
  'Gym Rules': 'জিমের নিয়মাবলি',
  'Continue to Dashboard': 'ড্যাশবোর্ডে যান',
  'Please add at least one hero image URL': 'কমপক্ষে একটি হিরো ইমেজের URL দিন',
  'Hero images updated': 'হিরো ছবিগুলো আপডেট হয়েছে',
  'Failed to update hero images': 'হিরো ছবি আপডেট করা যায়নি',
  'Edit Hero': 'হিরো সম্পাদনা',
  'Edit Hero Images': 'হিরো ছবি সম্পাদনা',
  'Slide {index}': 'স্লাইড {index}',
  'Slide title': 'স্লাইড শিরোনাম',
  'Image URL': 'ইমেজ URL',
  'Save': 'সংরক্ষণ',
  'Payment Verification': 'পেমেন্ট যাচাই',
  'Are you sure you want to {action}?': 'আপনি কি নিশ্চিত যে {action} করতে চান?',
  'Proceed': 'এগিয়ে যান',
  'Payment verification updated.': 'পেমেন্ট যাচাই আপডেট হয়েছে।',
  'Failed to verify payment': 'পেমেন্ট যাচাই করতে ব্যর্থ হয়েছে',
  'confirm': 'নিশ্চিত',
  'mark error': 'ত্রুটি চিহ্নিত',
  'Pending Payment Verifications': 'অপেক্ষমান পেমেন্ট যাচাই',
  'Primary admin verification required': 'প্রাইমারি অ্যাডমিন যাচাই প্রয়োজন',
  'Profile Photo': 'প্রোফাইল ছবি',
  'Upload Photo': 'ছবি আপলোড করুন',
  'Change Photo': 'ছবি পরিবর্তন করুন',
  'Date of Birth': 'জন্মতারিখ',
  'Select DOB': 'dd/mm/yyyy নির্বাচন করুন',
  'DOB is required': 'জন্মতারিখ দেওয়া বাধ্যতামূলক',
  'Gallery permission is required to upload profile photo.': 'প্রোফাইল ছবি আপলোড করতে গ্যালারির অনুমতি প্রয়োজন।',
  'Could not process selected photo. Please try another image.': 'নির্বাচিত ছবি প্রক্রিয়া করা যায়নি। অনুগ্রহ করে অন্য ছবি দিন।',
  'Forgot Password': 'পাসওয়ার্ড ভুলে গেছেন',
  'Verify with DOB and set a new secure password': 'জন্মতারিখ যাচাই করে নতুন নিরাপদ পাসওয়ার্ড সেট করুন',
  'Verify with phone OTP and set a new secure password': 'ফোন ওটিপি যাচাই করে নতুন নিরাপদ পাসওয়ার্ড সেট করুন',
  'Send OTP': 'ওটিপি পাঠান',
  'Resend OTP': 'আবার ওটিপি পাঠান',
  'Resend OTP in {seconds}s': '{seconds} সেকেন্ড পরে আবার ওটিপি পাঠানো যাবে',
  'Did not receive OTP? You can resend now.': 'ওটিপি পাননি? এখন আবার পাঠাতে পারেন।',
  'Enter OTP': 'ওটিপি লিখুন',
  'OTP sent to your registered phone': 'আপনার নিবন্ধিত ফোনে ওটিপি পাঠানো হয়েছে',
  'Failed to send OTP': 'ওটিপি পাঠাতে ব্যর্থ হয়েছে',
  'Reset Password': 'পাসওয়ার্ড রিসেট করুন',
  'Password reset successful. Please login with your new password.': 'পাসওয়ার্ড সফলভাবে রিসেট হয়েছে। নতুন পাসওয়ার্ড দিয়ে লগইন করুন।',
  'Failed to reset password': 'পাসওয়ার্ড রিসেট করতে ব্যর্থ হয়েছে',
  'Change Password': 'পাসওয়ার্ড পরিবর্তন',
  'Set a strong password for better account security': 'অ্যাকাউন্টের নিরাপত্তার জন্য শক্তিশালী পাসওয়ার্ড সেট করুন',
  'Current Password': 'বর্তমান পাসওয়ার্ড',
  'New Password': 'নতুন পাসওয়ার্ড',
  'Confirm New Password': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
  'Update Password': 'পাসওয়ার্ড আপডেট করুন',
  'Password changed successfully': 'পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে',
  'Failed to change password': 'পাসওয়ার্ড পরিবর্তন করতে ব্যর্থ হয়েছে',
  'Password checker': 'পাসওয়ার্ড যাচাই',
  'Password is too weak': 'পাসওয়ার্ড খুব দুর্বল',
  'At least 8 characters': 'কমপক্ষে ৮টি অক্ষর',
  'At least one uppercase letter': 'কমপক্ষে একটি বড় হাতের অক্ষর',
  'At least one lowercase letter': 'কমপক্ষে একটি ছোট হাতের অক্ষর',
  'At least one number': 'কমপক্ষে একটি সংখ্যা',
  'At least one special character': 'কমপক্ষে একটি বিশেষ চিহ্ন',
  'No spaces': 'কোনো স্পেস নয়',
  'More character variety': 'আরও বৈচিত্র্যময় অক্ষর ব্যবহার করুন',
  'Avoid common words or patterns': 'সাধারণ শব্দ বা প্যাটার্ন এড়িয়ে চলুন',
  'Gallery permission is required to upload hero image.': 'হিরো ছবি আপলোড করতে গ্যালারির অনুমতি প্রয়োজন।',
  'Could not process selected image. Please try another hero image.': 'নির্বাচিত ছবি প্রক্রিয়া করা যায়নি। অনুগ্রহ করে অন্য হিরো ছবি দিন।',
  'Selected hero image is too large. Please choose a smaller image.': 'নির্বাচিত হিরো ছবিটি খুব বড়। অনুগ্রহ করে ছোট ছবি বেছে নিন।',
  'Pick Hero Image': 'হিরো ছবি বাছাই করুন',
  'Membership Timeline': 'মেম্বারশিপ টাইমলাইন',
  '1-7: Standard fee Rs.700': '১-৭: স্ট্যান্ডার্ড ফি Rs.700',
  '1-7: Standard Fee Rs.700': '১-৭: স্ট্যান্ডার্ড ফি Rs.700',
  '8+: Rs.5/day late fee': '৮+: প্রতিদিন Rs.5 লেট ফি',
  'Total Rs.{amount}': 'মোট Rs.{amount}',
  'New Message': '\u09a8\u09a4\u09c1\u09a8 \u09ac\u09be\u09b0\u09cd\u09a4\u09be',
  'You have a new message.': '\u0986\u09aa\u09a8\u09be\u09b0 \u098f\u0995\u099f\u09bf \u09a8\u09a4\u09c1\u09a8 \u09ac\u09be\u09b0\u09cd\u09a4\u09be \u098f\u09b8\u09c7\u099b\u09c7\u0964',
  'New Notification': '\u09a8\u09a4\u09c1\u09a8 \u09a8\u09cb\u099f\u09bf\u09ab\u09bf\u0995\u09c7\u09b6\u09a8',
  'You have a new notification.': '\u0986\u09aa\u09a8\u09be\u09b0 \u098f\u0995\u099f\u09bf \u09a8\u09a4\u09c1\u09a8 \u09a8\u09cb\u099f\u09bf\u09ab\u09bf\u0995\u09c7\u09b6\u09a8 \u098f\u09b8\u09c7\u099b\u09c7\u0964',
  'New Announcement': '\u09a8\u09a4\u09c1\u09a8 \u0998\u09cb\u09b7\u09a3\u09be',
  'A new announcement is available.': '\u098f\u0995\u099f\u09bf \u09a8\u09a4\u09c1\u09a8 \u0998\u09cb\u09b7\u09a3\u09be \u09aa\u09be\u0993\u09df\u09be \u0997\u09c7\u099b\u09c7\u0964',
  'Seen': '\u09a6\u09c7\u0996\u09be \u09b9\u09df\u09c7\u099b\u09c7',
  'Open': '\u0996\u09c1\u09b2\u09c1\u09a8',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function interpolate(template: string, vars?: Record<string, string | number>) {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? `{${key}}`));
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('en');

  useEffect(() => {
    (async () => {
      try {
        const stored = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
        if (stored === 'en' || stored === 'bn') {
          setLanguageState(stored);
        }
      } catch (error) {
        console.log('Failed to load language:', error);
      }
    })();
  }, []);

  const setLanguage = async (nextLanguage: AppLanguage) => {
    setLanguageState(nextLanguage);
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
    } catch (error) {
      console.log('Failed to persist language:', error);
    }
  };

  const t = useMemo(() => {
    return (key: string, vars?: Record<string, string | number>) => {
      if (language !== 'bn') {
        return interpolate(key, vars);
      }
      const translated = BN_TRANSLATIONS[key] || key;
      return interpolate(translated, vars);
    };
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      languageLabel: LANGUAGE_LABELS[language],
    }),
    [language, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

